# Generated by Django 6.0.2 on 2026-05-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactquery',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
